import socket
server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server_socket.bind(("127.0.0.1", 12345))
server_socket.listen(1)
print("Server is waiting...")
conn, addr = server_socket.accept()
print("Connected by", addr)
data = conn.recv(1024)
print("Client says:", data.decode())
conn.send("Hello Client!".encode())
conn.close()
server_socket.close()
